#!/bin/bash
# Does every command wsl.ps1 knows exist everywhere it should, with the same
# words? The menu is the source; the README table and the commands page (its
# table, its section, its sample menu) are the copies that drift.
#
# It reads, it never writes: safe to run anywhere, on any branch.
#
# Usage: bash tests/doc-drift.sh
set -u

# From this file's own folder, two levels up: tests/ sits at the root.
cd "$(dirname "$0")/.." || exit 1

ps=$(tr -d '\r' < wsl.ps1)
drift=0
names=$(printf '%s\n' "$ps" | sed -n 's/^ *Add("\([a-z_]*\)".*/\1/p')

printf "%-14s %-8s %-7s %-7s %-7s %-8s %-8s\n" COMMAND README TABLE SECTION SAMPLE WHAT@README WHAT@PAGE
while read -r name; do
    [ -z "$name" ] && continue
    what=$(printf '%s\n' "$ps" | sed -n "s/.*Add(\"$name\", *\"\([^\"]*\)\".*/\1/p")

    ok() { if [ "$1" -gt 0 ]; then echo ok; else echo MISSING; drift=1; fi; }
    r=$(ok "$(grep -c "wsl\.ps1 $name\`\](docs/wsl/commands.md#$name)" README.md)")
    t=$(ok "$(grep -c "wsl\.ps1 $name\`\](#$name)" docs/wsl/commands.md)")
    s=$(ok "$(grep -c "^## \`$name\`" docs/wsl/commands.md)")
    # the sample line, whole: name AND description, spaces included
    sm=$(ok "$(grep -cF "$(printf '%-12s %s' "$name" "$what")" docs/wsl/commands.md)")
    wr=$(ok "$(grep -cF "| $what |" README.md)")
    wt=$(ok "$(grep -cF "| $what |" docs/wsl/commands.md)")
    { [ "$wr" = "MISSING" ] || [ "$wt" = "MISSING" ]; } && drift=1
    printf "%-14s %-8s %-7s %-7s %-7s %-8s %-8s\n" "$name" "$r" "$t" "$s" "$sm" "$wr" "$wt"
done <<< "$names"

# And the other way round: a command the docs still offer that wsl.ps1 no
# longer knows. The loop above reads the menu and cannot see one - all three
# copies are checked. The docs tables are matched on their own shape -
# ".\wsl.ps1 <name>" - so that prose naming wsl.ps1 without the dot-slash is not
# read as a command.
while read -r name; do
    grep -q "Add(\"$name\"" wsl.ps1 || {
        echo "  EXTRA: '$name' is offered by the docs, and wsl.ps1 does not know it"
        drift=1
    }
done < <(grep -ohE '\\wsl\.ps1 [a-z_]+' README.md docs/wsl/commands.md | awk '{print $2}' | sort -u)

# The sample menu on the commands page is a copy too, and the one that drifts
# most easily: it is regenerated by hand. That block only, from the title down
# to its footer - the page documents other menus of its own, drawn the same way
# at the same indent, and their rows are not commands of wsl.ps1. The title is
# the anchor: a moved title leaves the block empty, and empty is reported rather
# than passed - a check that reads nothing says nothing.
SampleMenu=$(awk '/^WSL Stack$/,/^  up\/down to move/' docs/wsl/commands.md | grep -oE '^ {4}[a-z_]+ ' | tr -d ' ' | sort -u)
if [ -z "$SampleMenu" ]; then
    echo "  EXTRA: no sample menu found on the commands page - this check read nothing"
    drift=1
fi
while read -r name; do
    [ -z "$name" ] && continue
    grep -q "Add(\"$name\"" wsl.ps1 || {
        echo "  EXTRA: the sample menu shows '$name', and wsl.ps1 does not know it"
        drift=1
    }
done <<< "$SampleMenu"

echo
[ "$drift" -eq 0 ] && echo "VERDICT: no drift" || echo "VERDICT: drift"
exit $drift
